/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hbv201G.yatzeeUtlit;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * 
 * UtlitYatzee sýnir notendaviðmót fyrir yatzee leikinn.
 * @author Elías Jónsson, Háskóli Íslands, elj31@hi.is.
 * @version 4
 * 
 * Keyrsla: ég bjó til .jar skrá sem er í dist með 
 * Clean og build og síðan exportaði úr Netbeans.
 * Notast við OS X Yosemite stýrikerfi og 
 * Java útgáfu 1.7.0_51
 * 
 * Dagsetning: 17/04/2015
 * 
 * Forritið: Sígildi leikurinn, Yatzee.
 * 
 */

/**
 * 
 * Hlutverk Fjolspilunarvalmynd er að sjá um notendaviðmót
 * hluta leiksins þegar notandi ákveður hvort hann eigi að
 * spila einn eða við einhvern annan. 
 * 
 */
public class Fjolspilunarvalmynd extends javax.swing.JFrame {
    
    UtlitYatzee vUtlitYatzee;
    /**
     * vUtlitYatzee er hlutur af taginnu UtlitYatzee
     * sem inniheldur viðmót leksins á meðan leikurinn Yatzee
     * er spilaður. Inniheldur JFrame.
     */
    
    /**
     * Creates new form Fjolspilunarvalmynd
     */
    public Fjolspilunarvalmynd() {
        initComponents();
        initMidjustilla();

    }
    /**
     * Miðjustillir jFrame-inn á skjá notanda.
     */
    private void initMidjustilla()
    {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getWidth()/2,
                dim.height/2-this.getHeight()/2);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpilaEinn = new javax.swing.JButton();
        jComputer = new javax.swing.JButton();
        jTilBaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSpilaEinn.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jSpilaEinn.setText("Spila einn");
        jSpilaEinn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpilaEinnActionPerformed(evt);
            }
        });

        jComputer.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jComputer.setText("Spila við tölvu");
        jComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComputerActionPerformed(evt);
            }
        });

        jTilBaka.setText("Til baka");
        jTilBaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTilBakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComputer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpilaEinn, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jTilBaka)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jSpilaEinn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTilBaka)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Lætur leikmann spila Yatzee þar sem hann spilar ekki við neinn ef hann
     * smellir á "Spila einn" hnappinn.
     * @param evt er atburðurinn sem var búinn til.
     */
    private void jSpilaEinnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpilaEinnActionPerformed
        setVisible(false);
        vUtlitYatzee = new UtlitYatzee(false);
        vUtlitYatzee.setVisible(true);
    }//GEN-LAST:event_jSpilaEinnActionPerformed
    /**
     * Lætur leikmann spila Yatzee þar sem hann spilar við tölvu ef hann
     * smellir á "Spila við tölvu" hnappinn
     * @param evt er atburðurinn sem var búinn til.
     */
    private void jComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComputerActionPerformed
        setVisible(false);
        vUtlitYatzee = new UtlitYatzee(true);
        vUtlitYatzee.setVisible(true);
    }//GEN-LAST:event_jComputerActionPerformed
    /**
     * Lætur leikmann far til baka í upphafsvalmyndina ef smellt er á 
     * "Til baka" hnappinn.
    */
    private void jTilBakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTilBakaActionPerformed
        Upphafsvalmynd vUpphafsValmynd = new Upphafsvalmynd();
        setVisible(false);
        vUpphafsValmynd.setVisible(true);
    }//GEN-LAST:event_jTilBakaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jComputer;
    private javax.swing.JButton jSpilaEinn;
    private javax.swing.JButton jTilBaka;
    // End of variables declaration//GEN-END:variables
}
