/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hbv201G.yatzeeUtlit;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * 
 * UtlitYatzee sýnir notendaviðmót fyrir yatzee leikinn.
 * @author Elías Jónsson, Háskóli Íslands, elj31@hi.is.
 * @version 4
 * 
 * Keyrsla: ég bjó til .jar skrá sem er í dist með 
 * Clean og build og síðan exportaði úr Netbeans.
 * Notast við OS X Yosemite stýrikerfi og 
 * Java útgáfu 1.7.0_51
 * 
 * Dagsetning: 17/04/2015
 * 
 * Forritið: Sígildi leikurinn, Yatzee.
 * 
 */

/**
 * 
 * Hlutverk UtlitHowToPlay er að sjá um notendaviðmót
 * hluta leiksins þegar notandi vill fá upplýsingar um
 * hvernig eigi að spila Yatzee leikinn. Inniheldur JDialog
 * 
 */
public class UtlitHowToPlay extends javax.swing.JDialog {

    /**
     * Creates new form UtlitHowToPlay
     */
    /**
     * Upphafstillir UtlitHowToPlay dialog-inn staðsetningu, 
     * hluti á honum og fleira.
     * @param parent er ramminn sem dialog-inn
     * á að birtast af.
     * @param modal boolean breyta.
     */
    public UtlitHowToPlay(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initTextPane();
        initMidjustilla();
    }
    /**
     * Lætur texta reitinn vera gegnsæjan og skrunaður efst.
     */
    public void initTextPane()
    {
        jHowToPlayTextPane.setBackground(new Color(0,0,0,0));
        jHowToPlayTextPane.setOpaque(false);
        jHowToPlayTextPane.setCaretPosition(0);       
    }
    /**
     * Miðjustillir jFrame-inn á skjá notanda.
     */    
    public void initMidjustilla()
    {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getWidth()/2,
                dim.height/2-this.getHeight()/2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jHowToPlayTextPane = new javax.swing.JTextPane();
        jTitill = new javax.swing.JLabel();
        jBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jHowToPlayTextPane.setText("1. Til þess að byrja nýjan leik smellir maður á\n    \"Byrja nýjan leik\" eða á Skrá-> Nýr leikur\n    á valmyndarslánni.\n\n2. Til þess að frysta teninga ýtir maður annað hvort á \n    teningana sjálfa eða fer í valmyndarslánna efst og \n    ýtir á aðgerðir->Frysta teninga og velur síðan \n    teninginn sem á að frysta.\n\n3. Til þess að kasta teningunum smellir maður annað\n    hvort á \"Kasta Teningum\" hnappinn eða á Aðgerðir\n    -> Kasta Teningum á valmyndarslánni.\n\n4. Ef spilað er við tölvuna er nauðsynlegt að bíða eftir að \n    tölvan klári sinn leik, en síðasti leikur tölvunnar er litaður \n    með rauðu á stigatöfluna.\n\n5. Til þess að Hætta í Yatzze leik er annað hvort smellt á \n    hætta eða á skrá->Hætta leik í valmyndarslánni.\n\n6. Hægt er að komast aftur í aðalvalmynd með því að\n    smella á \"Aðalvalmynd\" eða á Skrá->Aðalvalmynd\n    á valmyndarslánni.\n\n7. Þegar leik lýkur er notanda tilkynnt hvort hann hafi\n    unnið tölvuna, ef hann valdi að keppa við tölvuna.\n    Ef hann síðar smellur á \"Halda áfram\" hnappinn er\n    honum tilkynnt um hvot hann hafi komist á topp 10\n    listann. Notanda er strax tilkynnt að leik loknum hvort\n    hann hafi komist á topp 10 listann ef hann valdi að\n    spila einn.\n");
        jScrollPane1.setViewportView(jHowToPlayTextPane);

        jTitill.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jTitill.setText("Hvernig spilar maður Yatzee?");

        jBack.setText("Fara aftur í leik");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jTitill, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTitill)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBack, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Þegar smellt er á "Fara aftur í leik" hnappinn hverfur dialoginn.
     * @param evt  er atburðurinn sem búinn er til.
     */
    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        dispose();
    }//GEN-LAST:event_jBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtlitHowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtlitHowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtlitHowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtlitHowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UtlitHowToPlay dialog = new UtlitHowToPlay(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JTextPane jHowToPlayTextPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTitill;
    // End of variables declaration//GEN-END:variables
}
