/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hbv201G.yatzeeUtlit;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 * 
 * UtlitYatzee sýnir notendaviðmót fyrir yatzee leikinn.
 * @author Elías Jónsson, Háskóli Íslands, elj31@hi.is.
 * @version 4
 * 
 * Keyrsla: ég bjó til .jar skrá sem er í dist með 
 * Clean og build og síðan exportaði úr Netbeans.
 * Notast við OS X Yosemite stýrikerfi og 
 * Java útgáfu 1.7.0_51
 * 
 * Dagsetning: 17/04/2015
 * 
 * Forritið: Sígildi leikurinn, Yatzee.
 * 
 */

/**
 * 
 * Hlutverk UtlitSigurvegari er að sjá um notendaviðmót
 * hluta leiksins þegar notanda er tilkynnt um það
 * hvort hann hafi unnið tölvuna eða ekki. Innihdlur JDialog
 */
public class UtlitSigurvegari extends javax.swing.JDialog {

    String leikmadurStig;
    String tolvaStig;
    Frame parent;
    /**
     * Creates new form UtlitSigurvegari
     */
    /**
     * Upphafstillir UtlitSigurvegari dialog-inn staðsetningu, 
     * hluti á honum og fleira.
     * @param parent er ramminn sem dialog-inn
     * á að birtast af.
     * @param modal boolean breyta.
     * @param lStig eru stig notanda.
     * @param tStig eru stig tölvunnar.
     */
    public UtlitSigurvegari(java.awt.Frame parent, boolean modal,int lStig, int tStig) {
        super(parent, modal);
        this.leikmadurStig = Integer.toString(lStig);
        this.tolvaStig = Integer.toString(tStig);
        this.parent = parent;
        initComponents();
        skrifaUrslit();
        initMidjustilla();
    }
    
    /**
     * Miðjustillir jFrame-inn á skjá notanda.
     */ 
    public void initMidjustilla()
    {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getWidth()/2,
                dim.height/2-this.getHeight()/2);
    }
    
    /**
     * Fallið lætur notanda vita hvort hann hafi unnið tölvuna eða ekki.
     */
    public void skrifaUrslit()
    {
        int lStig = Integer.parseInt(leikmadurStig);
        int tStig = Integer.parseInt(tolvaStig);
        if(lStig>tStig)
            jUrslitBordi.setText("Til hamingju þú vannst!");
        else if(lStig<tStig)
            jUrslitBordi.setText("Þú tapaðir, því miður.");
        else
            jUrslitBordi.setText("Þetta var hnífjafnt.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jUrslitBordi = new javax.swing.JLabel();
        jLeikmadur = new javax.swing.JLabel();
        jTolva = new javax.swing.JLabel();
        jContinue = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Þú fékkst 0 stig");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yatzee");

        jUrslitBordi.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jUrslitBordi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLeikmadur.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLeikmadur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLeikmadur.setText("Þú fékkst " + this.leikmadurStig + " stig.");

        jTolva.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jTolva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTolva.setText("Tölvan fékk " + this.tolvaStig + " stig.");

        jContinue.setText("Halda áfram");
        jContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jUrslitBordi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLeikmadur, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTolva, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jUrslitBordi)
                .addGap(49, 49, 49)
                .addComponent(jLeikmadur)
                .addGap(32, 32, 32)
                .addComponent(jTolva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Opnar Topp 10 listann ef smellt er á "Halda áfram" hnappinn.
     * @param evt atburðurinn sem er búinn til.
     */
    private void jContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContinueActionPerformed
        Topp10Listi topp10Vidmot = new Topp10Listi(true, Integer.parseInt(leikmadurStig));
        topp10Vidmot.setVisible(true);
        topp10Vidmot.setAlwaysOnTop (true);
        setVisible(false);
        parent.setVisible(false);
    }//GEN-LAST:event_jContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtlitSigurvegari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtlitSigurvegari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtlitSigurvegari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtlitSigurvegari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UtlitSigurvegari dialog = new UtlitSigurvegari(new javax.swing.JFrame(), true,0 ,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jContinue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLeikmadur;
    private javax.swing.JLabel jTolva;
    private javax.swing.JLabel jUrslitBordi;
    // End of variables declaration//GEN-END:variables
}
