/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hbv201G.yatzeeUtlit;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * 
 * UtlitYatzee sýnir notendaviðmót fyrir yatzee leikinn.
 * @author Elías Jónsson, Háskóli Íslands, elj31@hi.is.
 * @version 4
 * 
 * Keyrsla: ég bjó til .jar skrá sem er í dist með 
 * Clean og build og síðan exportaði úr Netbeans.
 * Notast við OS X Yosemite stýrikerfi og 
 * Java útgáfu 1.7.0_51
 * 
 * Dagsetning: 17/04/2015
 * 
 * Forritið: Sígildi leikurinn, Yatzee.
 * 
 */

/**
 * 
 * Hlutverk UtlitLeikreglur er að sjá um notendaviðmót
 * hluta leiksins þegar notandi vill fá leikreglur
 * Yatzee leiksins. Inniheldur JDialog.
 */
public class UtlitLeikreglur extends javax.swing.JDialog {

    /**
     * Creates new form UtlitLeikreglur
     */
    /**
     * Upphafstillir UtlitLeikreglur dialog-inn staðsetningu, 
     * hluti á honum og fleira.
     * @param parent er ramminn sem dialog-inn
     * á að birtast af.
     * @param modal boolean breyta.
     */
    public UtlitLeikreglur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initTextPane();
        initMidjustilla();
    }
    
     /**
     * Lætur texta reitinn vera gegnsæjan og skrunaður efst.
     */
    public void initTextPane()
    {
        jRulesTextPane.setBackground(new Color(0,0,0,0));
        jRulesTextPane.setOpaque(false);
        jRulesTextPane.setCaretPosition(0);       
    }
    /**
     * Miðjustillir jFrame-inn á skjá notanda.
     */ 
    public void initMidjustilla()
    {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getWidth()/2,
                dim.height/2-this.getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitill = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRulesTextPane = new javax.swing.JTextPane();
        jBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTitill.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jTitill.setText("Leikreglur");

        jRulesTextPane.setText("Reglurnar eru þannig að leikmaður reynir að fá sem  flest stig en til þess fær hann þrjú köst í hverri  umferð. Í hverri umferð á leikmaðurinn að reyna að ná fram ein- hverri af eftirfarandi samsetningum en hverja samsetningu er hinsvegar bara hægt að ná einu sinni í hverjum leik.\n\nÁsar: Reynt að safna sem flestum ásum. Stigin eru reiknuð sem summa teninga með ása eftir þrjú köst.\n\nTvistar: Reynt að safna sem flestum tvistum. Stigin eru reiknuð sem summa teninga með tvo eftir þrjú köst.\n\nÞristar: Reynt að safna sem flestum þristum. Stigin eru reiknuð sem summa teninga með þrjá eftir þrjú köst.\n\nFjarkar: Reynt að safna sem flestum fjörkum. Stigin eru reiknuð sem summa teninga með fjóra eftir þrjú köst.\n\nFimmur: Reynt að safna sem flestum fimmum. Stigin eru reiknuð sem summa teninga með fimm eftir þrjú köst.\n\nSexur: Reynt að safna sem flestum Sexum. Stigin eru reiknuð sem summa teninga með sex eftir þrjú köst.\n\nEitt par: Tveir teningar sýna sömu töluna. Stigin eru reiknuð sem summa þessara tveggja teninga.\n\nTvö pör: Þegar tveir teningar sýna sömu töluna ásamt því að aðrir tveir teningar sýna sömu töluna. Stigin eru reiknuð sem summa þessara fjögurra teninga.\n\nÞrír eins: Þrír eða fleiri teningar sýna sömu töluna. Stigin eru reiknuð sem summa þessara þriggja teninga.\n\nFjórir eins: Fjórir teningar sýna sömu töluna. Stigin eru reiknuð sem summa þessara fjögurra teininga.\n\nLítil röð: Fimm teningar mynda röð (1, 2, 3, 4, 5),  15 stig eru gefin fyrir litla röð.\n\nStór röð: Fimm teningar mynda röð (2, 3, 4, 5, 6),  20 stig eru gefin fyrir lstóraröð.\n\nFullt Hús: Ein þrenna og eitt par mynda fullt hús. summa þessara teninga gefa stigin fyrir fullt hús.\n\nTaka Sénsinn: Það er þegar allir teningarnir eru lagðir saman og oftast notað þegar að leikmaður lendir í vandræðum og getur lítið gert úr þeim möguleikum sem teningarnir bjóða upp á eftir fyrsta kast.\n\nYatzee: Þegar allir teningarnir eru eins. 50 stig eru gefin og er þá hæsta stigagjöfin sem hægt er að fá.");
        jScrollPane1.setViewportView(jRulesTextPane);

        jBack.setText("Fara aftur í leik");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jTitill))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jBack)))
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTitill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBack, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Þegar smellt er á "Fara aftur í leik" hnappinn hverfur dialoginn.
     * @param evt  er atburðurinn sem búinn er til.
     */
    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        dispose();
    }//GEN-LAST:event_jBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtlitLeikreglur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtlitLeikreglur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtlitLeikreglur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtlitLeikreglur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UtlitLeikreglur dialog = new UtlitLeikreglur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JTextPane jRulesTextPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTitill;
    // End of variables declaration//GEN-END:variables
}
